apiVersion: v1
kind: Service
metadata:
  name: podinfo-stable
  labels:
    app.kubernetes.io/name: podinfo
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: http
      protocol: TCP
      name: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: podinfo
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-canary
  labels:
    app.kubernetes.io/name: podinfo
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: http
      protocol: TCP
      name: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: podinfo
