apiVersion: v1
appVersion: 1.11.2
deprecated: true
description: DEPRECATED Envoy is an open source edge and service proxy, designed for
  cloud-native applications.
home: https://www.envoyproxy.io/
icon: https://avatars0.githubusercontent.com/u/30125649
keywords:
- envoy
- proxy
name: envoy
sources:
- https://github.com/envoyproxy/envoy
version: 1.9.4
