apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: envoy
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: envoy
subjects:
- kind: ServiceAccount
  name: envoy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy
